### PR TITLE
Added switch

### PR DESCRIPTION
**Pull request by SkzKatsushiro**
- Added - switch to the scrip. It asks the user if the SteamLibrary is in the default location if yes it runs the scrip in runs same as the old else user needs to provide the file path to library.

### CODE REVIEW

**Comment by S5SS** [comment]
Hey thanks for the addition 👍. I have a few questions about it first though, can you dm me on discord when your around so we can talk a bit

**Comment by SkzKatsushiro** [comment]
Sure

**Comment by S5SS** [comment]
Actually when your available here works too, Im just wondering about this SteamLibrary folder, is this a fix that works on your steam setup?

**Comment by S5SS** [comment]
I've heard that apparently you can have multiple steamapps install locations so I was thinking Id like to rework the logic a bit to move the code you submitted into the dok folder not found if statement so that it only asks this if its automatic detection didn't work and to change it so it asks for the dok folder path instead of SteamLibrary since its possible a user might put a path to a SteamLibrary that doesn't have dok in it.

**Comment by SkzKatsushiro** [comment]
The fix is for steam only. In my case I moved the install steam dir to a
different drive S:/SteamLibrary. To reflect that I added the fix to prompt
the user for the altered path.

**Comment by SkzKatsushiro** [comment]
Sorry I will pm you latter. I am at work...

**Comment by S5SS** [comment]
OK np

**Pull request merged**
